version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-ingest}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ingest}
      POSTGRES_DB: ${DB_NAME:-ingest}
    ports:
      - "${INGEST_DB_PORT:-15432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
