namespace: personal

db:
  # JDBC URL for the external Postgres database
  url: ""
  # Database user
  username: ""
  # Database password
  password: ""

ingestService:
  image: ingest-service:latest
  schedule: "*/10 * * * *"
  hostPaths:
    incoming: /incoming
    processed: /processed
