apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
  namespace: {{ .Values.namespace }}
  labels:
    app: ingest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-service
  template:
    metadata:
      labels:
        app: ingest-service
    spec:
      containers:
        - name: ingest-service
          image: {{ .Values.ingestService.image }}
          env:
            - name: DB_URL
              value: {{ printf "jdbc:postgresql://%s-postgresql.%s.svc.cluster.local:5432/%s" .Release.Name .Values.namespace .Values.postgresql.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.ingestService.env.DB_USER | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ingest-db
                  key: password
          ports:
            - containerPort: 8080
