apiVersion: v1
kind: Secret
metadata:
  name: teller-poller
  namespace: {{ .Values.namespace }}
stringData:
  tokens: {{ .Values.secrets.tellerPoller.tokens | quote }}
  cert.pem: {{ .Values.secrets.tellerPoller.cert | quote }}
  key.pem: {{ .Values.secrets.tellerPoller.key | quote }}
