apiVersion: apps/v1
kind: Deployment
metadata:
  name: teller-poller
  namespace: {{ .Values.namespace }}
  labels:
    app: teller-poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teller-poller
  template:
    metadata:
      labels:
        app: teller-poller
    spec:
      containers:
        - name: teller-poller
          image: {{ .Values.tellerPoller.image }}
          env:
            - name: DB_URL
              value: {{ .Values.db.url | quote }}
            - name: DB_USER
              value: {{ .Values.db.username | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ingest-db
                  key: password
            - name: TELLER_TOKENS
              valueFrom:
                secretKeyRef:
                  name: teller-poller
                  key: tokens
            - name: TELLER_CERT_FILE
              value: /var/run/secrets/teller/cert.pem
            - name: TELLER_KEY_FILE
              value: /var/run/secrets/teller/key.pem
            - name: POLL_INTERVAL
              value: {{ .Values.tellerPoller.pollingInterval | quote }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: teller-poller-cert
              mountPath: /var/run/secrets/teller
              readOnly: true

      volumes:
        - name: teller-poller-cert
          secret:
            secretName: teller-poller